import { Providers } from '@/components/providers';
// import Auth from '@/protected/Auth';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function LoginLayout({ children }) {
  return <main>{children}</main>;
}
